name: deploy at EC2

on:
  pull_request:
    branches: 
      - main
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 인스턴스 pem key
          port: 22 # 접속포트
          script: | # 실행할 스크립트
            cd /home/ubuntu/rg-front
            git pull origin main
            pm2 kill
            yarn install
            
            # lint 결과에 따라 이후 명령 실행 여부 결정
            if yarn lint; then
              echo "Lint passed, proceeding with build."
              yarn build
              pm2 start "yarn start"
            else
              echo "Lint failed, stopping process."
              exit 1
            fi
