name: Jest_Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.17.0"

      - name: yarn_install
        run: yarn install --immutable --immutable-cache --check-cache

      - name: run_test_code
        run: yarn test:ci
        env:
          AWS_CLOUDFRONT_HOSTNAME: ${{secrets.AWS_CLOUDFRONT_HOSTNAME}}
          NEXT_PUBLIC_AWS_CLOUDFRONT_URL: ${{secrets.NEXT_PUBLIC_AWS_CLOUDFRONT_URL}}

      - name: if_fail
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            console.log(pull_number, ref.split("/"), github.ref)
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body : "테스트 코드에 실패했습니다.",
              event : "REQUEST_CHANGES"
            })
            await github.pulls.update({
              ...context.repo,
              pull_number,
              state: "closed"
            })
        if: failure()
